### ISSUE TITLE
ProxyManager 2.3 does not follow Semantic Versioning

### ISSUE THREAD

**Issue by timEulitz** [Ocramius/ProxyManager#455]
With all due respect for your work, I am also definitely hyped for PHP 7.4 but don't you think it's odd to release such a major change as a minor stable release when PHP 7.4 is still in an early alpha development phase?

Would it not make much more sense to make this version 3.0-dev, considering there is really no way this code can be executed on anything that could be remotely considered a stable production environment? This will definitely confuse a lot of people and it does not follow [semantic versioning](https://semver.org/), as you are breaking backwards compatibility which warrants a major release and not a minor one.

Again, no disrespect intended but I think that if possible, you should unpublish 2.3 and republish it as 3.0 or 3.0-dev until PHP 7.4 is actually finalized.

**Comment by Ocramius** [comment]
Hello,

According to SemVer, dependency upgrades are allowed in minor releases. We've documented this at https://www.doctrine-project.org/2017/07/25/php-7.1-requirement-and-composer.html

If you need PHP 7.1 or 7.2 support, please rely on `^2.2` or ``^2.1`.

 > as you are breaking backwards compatibility which warrants a major release and not a minor one.

No backwards compatibility was broken: inadvertently introduced BC breaks were fixed in `2.3.1` (released this morning).

**Comment by Ocramius** [comment]
Please also note that I regularly bump dependency requirements (including PHP version) in every minor release, and I kept doing that for years: if you suddenly got a problem due to this, please make sure that you are running `composer update` in a production-alike environment.

**Comment by timEulitz** [comment]
Hey, thanks for taking your time to get back to me. The explanation you linked does make sense and I was not aware of that, so thanks for clearing that up. I guess we have an issue in some composer.json file and I'll look into that.

However, I am still not sure what the point of releasing a stable release for a PHP version that is still in alpha and roughly 9 months away would be - you also did not do that for previous releases as far as I can see. That kind of reminds me of how people wrote books for PHP 6 before it came out and we all know what happened afterwards 😬. 

Anyway, it's not a big deal and you code argue that your code is stable by our current definition of PHP 7.4, I just think "you are asking for trouble" by doing this. If you want to elaborate on this train of thought, I'd be happy to hear you out, but I understand that arguing with strangers online can be a drag so not worries.

**Comment by Ocramius** [comment]
> However, I am still not sure what the point of releasing a stable release for a PHP version that is still in alpha and roughly 9 months away would be - you also did not do that for previous releases as far as I can see. That kind of reminds me of how people wrote books for PHP 6 before it came out and we all know what happened afterwards 😬.

Very good point. Right now, I needed this personally in order to start developing on PHP 7.4, but my main push is for stabilising the library onto the current PHP 7.4 dev branch (with weekly CI builds), as well as getting people ti try things out.

Specifically, if you run typed properties with ProxyManager 2.2.x, it will just explode spectacularly, while now it is possible to prototype freely.

I will keep a close eye on language changes BTW.

> I just think "you are asking for trouble" by doing this because it's bound to confuse people.

You will get this release only in two cases:

 1. You run PHP 7.4, and therefore you are already aware of what you are doing
 2. You ran `composer update --ignore-platform-reqs`, in which case you are bound to learn a lesson the hard way very soon.

**Comment by Slamdunk** [comment]
> but I understand that arguing with strangers online can be a drag so no worries if you don't feel like it.

:clap:

It's so rare to see a polite conversation in a controversial topic that I think you just earned @Ocramius respect in one phrase

**Comment by m47730** [comment]
i've just seen the "voodoo php magic" speech of Marco that i found inspiring and fun.
If i understand correctly ProxyManager do use magic, so (in my opinion) it's a task of a good maintainer try early version of PHP to catch explosion bugs as fast as possible.
So if you test and fix bugs here and then to comply with 7.4 so why not release it? It makes sense; it's simply unconditional trust on composer :-)

**Comment by Ocramius** [comment]
Yeh, the alternative was indeed to have the branch rot for another 9 months 😜

**Comment by timEulitz** [comment]
Hey, just as an update, I had another look at this and it turns out that `doctrine-migrations` 1.8 actually requires `"ocramius/proxy-manager": "^1.0|^2.0"` which is part of the reason why the issue appeared for us:

https://github.com/doctrine/migrations/blob/1.8/composer.json#L17

>You ran composer update --ignore-platform-reqs, in which case you are bound to learn a lesson the hard way very soon.

Yes, I think this is a flaw in our setup that has simply gone unnoticed for quite some time (mainly due to the misunderstanding of what warrants a BC break in semantic versioning). Our environments are Docker-based but Composer is executed on the host machine with the `--ignore-platform-reqs` option.

As far as I am concerned, this really just means that the only proper fix for this would be to run Composer inside of Docker rather than on the host machine and to drop the `--ignore-platform-reqs` parameter. So that definitely marks the end of this Github issue :ok_hand:.

>It's so rare to see a polite conversation in a controversial topic that I think you just earned @Ocramius respect in one phrase

I know it can be really frustrating to always be on the defense when you are really just providing some crazy shit for free, so I really just try not to be a nag and assume people know what they are doing. My initial post was worded a bit "demanding" which I didn't like after re-reading it again, so I wanted to make clear that this was not my intention.

**Comment by Ocramius** [comment]
> Our environments are Docker-based but Composer is executed on the host machine with the `--ignore-platform-reqs` option.

My suggestion here is to have a barebone box with  your PHP extensions, then running `docker run -v .:/app my-php-environment composer update` from there

**Comment by Taluu** [comment]
Or, to remove the `--ignore-platform-reqs` (I'm guilty of using it too because of docker and memcached...) and to add whatever is relevant to the `platform` config ?

**Comment by ricardofiorani** [comment]
So instead of "leave the branch to rot for another 9 months" it was decided to require an unreleased version of PHP, release a new version of this and introduce a problem to everyone who depends directly or indirectly to ProxyManager ?

With all due respect, every user of `doctrine/migrations` are going to have problems due to this unwise decision.

👏

**Comment by Taluu** [comment]
`doctrine/migrations` requires `^2.0.2`, not `^2.0`, so neither `2.1`, `2.2` or `2.3` will be used...

And as it was already said : as long as you don't use `--ignore-platform-reqs`, as the require states `^7.4`, composer won't install the new version. And that's it.

**Comment by Ocramius** [comment]
Locking here: @Taluu explained this correctly, use composer the way it is designed to be used (with SemVer version matchers).

**Comment by Ocramius** [comment]
To clarify, `^2.0.2` selects `>=2.0.2,<3.0.0`. This is correct, and you will get the newest `ocramius/proxy-manager` compatible with your project and environment constraints.

Ref: https://github.com/Ocramius/ProxyManager/issues/464#issuecomment-504587673
